<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="63684" started-at="2020-09-12T07:04:06Z" finished-at="2020-09-12T07:05:10Z">
    <groups>
    </groups>
    <test name="Test2" duration-ms="4164" started-at="2020-09-12T07:04:06Z" finished-at="2020-09-12T07:04:10Z">
      <class name="koch.com.ixigo.google">
        <test-method status="PASS" signature="driverSetup(java.lang.String, java.lang.String, java.lang.String, org.testng.ITestContext)[pri:0, instance:koch.com.ixigo.google@530612ba]" name="driverSetup" is-config="true" duration-ms="3517" started-at="2020-09-12T07:04:03Z" finished-at="2020-09-12T07:04:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[grid]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[docker]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[org.testng.TestRunner@30f842ca]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverSetup -->
        <test-method status="PASS" signature="verifyIxigoPageIsLoaded()[pri:0, instance:koch.com.ixigo.google@530612ba]" name="verifyIxigoPageIsLoaded" duration-ms="4128" started-at="2020-09-12T07:04:06Z" finished-at="2020-09-12T07:04:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIxigoPageIsLoaded -->
        <test-method status="PASS" signature="driverClose()[pri:0, instance:koch.com.ixigo.google@530612ba]" name="driverClose" is-config="true" duration-ms="82" started-at="2020-09-12T07:05:10Z" finished-at="2020-09-12T07:05:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverClose -->
      </class> <!-- koch.com.ixigo.google -->
    </test> <!-- Test2 -->
    <test name="Test" duration-ms="63684" started-at="2020-09-12T07:04:06Z" finished-at="2020-09-12T07:05:10Z">
      <class name="koch.com.ixigo.verifyIxigo">
        <test-method status="PASS" signature="verifyIxigoPageIsLoaded()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae]" name="verifyIxigoPageIsLoaded" duration-ms="8711" started-at="2020-09-12T07:04:06Z" finished-at="2020-09-12T07:04:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIxigoPageIsLoaded -->
        <test-method status="FAIL" signature="verifyPassangerDetailsAreAdded()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae]" name="verifyPassangerDetailsAreAdded" duration-ms="54929" started-at="2020-09-12T07:04:15Z" depends-on-methods="koch.com.ixigo.verifyIxigo.verifyIxigoPageIsLoaded" finished-at="2020-09-12T07:05:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verify From Place Acutual : IXG - Belgaum Expected is : PNQ - Pune expected [PNQ - Pune] but found [IXG - Belgaum]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verify From Place Acutual : IXG - Belgaum Expected is : PNQ - Pune expected [PNQ - Pune] but found [IXG - Belgaum]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at koch.com.ixigo.verifyIxigo.verifyPassangerDetailsAreAdded(verifyIxigo.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPassangerDetailsAreAdded -->
        <test-method status="SKIP" signature="verifyNonStopFlights()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae]" name="verifyNonStopFlights" duration-ms="0" started-at="2020-09-12T07:05:10Z" depends-on-methods="koch.com.ixigo.verifyIxigo.verifyPassangerDetailsAreAdded" finished-at="2020-09-12T07:05:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method verifyIxigo.verifyNonStopFlights()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method verifyIxigo.verifyNonStopFlights()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNonStopFlights -->
        <test-method status="SKIP" signature="verifyFlightsWithFareLessThanFiveThosuand()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae]" name="verifyFlightsWithFareLessThanFiveThosuand" duration-ms="0" started-at="2020-09-12T07:05:10Z" depends-on-methods="koch.com.ixigo.verifyIxigo.verifyNonStopFlights" finished-at="2020-09-12T07:05:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method verifyIxigo.verifyFlightsWithFareLessThanFiveThosuand()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method verifyIxigo.verifyFlightsWithFareLessThanFiveThosuand()[pri:0, instance:koch.com.ixigo.verifyIxigo@7dc222ae] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlightsWithFareLessThanFiveThosuand -->
      </class> <!-- koch.com.ixigo.verifyIxigo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
